name: GitHub Classroom Autograding - TP3

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  evaluacion-autograding:
    name: Autograding Tests - TP3
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configurar Permisos de Ejecución
        run: |
          chmod +x test.sh

      - name: Ejecutar Suite de Evaluación de TP3
        run: |
          ./test.sh
